version: '3.8'
services:
  authservice:
    build: 
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./authservice/.env
  relservice:
    build: 
      context: ./relservice
      dockerfile: Dockerfile
    env_file:
      - ./relservice/.env
    ports:
      - "8082:8082"
  ##gatewayservice:
    ##build: ./gateservice
    ##ports:
     ## - 8081:8081
##  user_db: 
##    image: mysql:8.0.34
##    environment:
##      MYSQL_ROOT_PASSWORD: root
##      MYSQL_USER: root
##      MYSQL_PASSWORD: root
##      MYSQL_DATABASE: golang-docker-user
##    container_name: golang-docker-db-rel
##    ports:
##      - 33066:3306
