version: '3.8'
services:
  authservice:
    build: 
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./authservice/.env
  ##gatewayservice:
    ##build: ./gateservice
    ##ports:
     ## - 8081:8081